spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 81

#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  type-aliases-package: com.itheima.domain
  mapper-locations: classpath:mapper/*Mapper.xml

